name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          usedocker: true
          docker_heroku_process_type: worker
          stack: "container"
          region: "eu"
        env:
          DYNAMIC_JSON_FILEID: ${{ secrets.DYNAMIC_JSON_FILEID }}
          GIT_REF: ${{ secrets.GIT_REF }}
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          heroku container:login
          echo "https://docs.google.com/uc?export=download&id=$DYNAMIC_JSON_FILEID" | aria2c --input-file=-
          docker build . -t registry.heroku.com/$HEROKU_APP_NAME/worker --progress=plain --build-arg GIT_REF=$GIT_REF
          docker push registry.heroku.com/$HEROKU_APP_NAME/worker
          heroku container:release worker -a $HEROKU_APP_NAME